- platform: template
  sensors:
    office_closet_door:
      friendly_name: "Office Closet Door"
      device_class: door
      value_template: >-
        {{ is_state("binary_sensor.office_closet_door_left", "on") or is_state("binary_sensor.office_closet_door_right", "on") }}
    bad_air:
      friendly_name: "Bad Air"
      value_template: >-
        {{ states("sensor.purpleair_aqi") | float > 50 }}

- platform: workday
  country: US
  province: CA
