- platform: myq
  username: !secret myq_username
  password: !secret myq_password
  type: chamberlain

- platform: group
  name: Living Room
  entities:
    - cover.living_room_left
    - cover.living_room_center
    - cover.living_room_right

- platform: group
  name: Office
  entities:
    - cover.office_left
    - cover.office_right

- platform: group
  name: Master Bedroom
  entities:
    - cover.master_bedroom_left
    - cover.master_bedroom_right
