- platform: huesensor

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: load_5m
    - type: processor_use

- platform: template
  sensors:
    open_windows_count:
      friendly_name: "Open Windows"
      entity_id: group.window_sensors
      value_template: >-
        {{ expand('group.window_sensors') | selectattr('state', 'eq', 'on') | list | length | int }}
      icon_template: >-
        {% if expand('group.window_sensors') | selectattr('state', 'eq', 'on') | list | length > 0 %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}

    open_doors_count:
      friendly_name: "Open Doors"
      entity_id: group.door_sensors
      value_template: >-
        {{ expand('group.door_sensors') | selectattr('state', 'eq', 'on') | list | length | int }}
      icon_template: >-
        {% if expand('group.door_sensors') | selectattr('state', 'eq', 'on') | list | length > 0 %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
