# General configuration
homeassistant:
  customize: !include customize.yaml
  elevation: !secret home_elevation
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  name: !secret home_name
  time_zone: America/Los_Angeles
  unit_system: imperial

# Base configuration
automation: !include_dir_merge_list automations
config:
frontend:
  themes: !include_dir_merge_named themes
history:
http:
  ssl_certificate: ssl/fullchain.pem
  ssl_key: ssl/privkey.pem
ios:
logbook:
lovelace:
  mode: yaml
mobile_app:
recorder:
  db_url: !secret mysql_url
script: !include_dir_merge_named scripts
sun:
system_health:
updater:

# Integrations
august: !include integrations/august.yaml
binary_sensor: !include integrations/binary_sensor.yaml
camera: !include integrations/camera.yaml
cover: !include integrations/cover.yaml
dyson: !include integrations/dyson.yaml
ecobee: !include integrations/ecobee.yaml
group: !include groups.yaml
hacs: !include integrations/hacs.yaml
homekit: !include integrations/homekit.yaml
input_boolean: !include integrations/input_boolean.yaml
light: !include integrations/light.yaml
octoprint: !include integrations/octoprint.yaml
scene: !include scenes.yaml
sensor: !include integrations/sensor.yaml
shell_command: !include integrations/shell_command.yaml
timer: !include integrations/timer.yaml
unifiprotect: !include integrations/unifiprotect.yaml
weather: !include integrations/weather.yaml
zone: !include integrations/zone.yaml

switch:
  - platform: flux
    lights:
      - light.sams_lamp
      - light.ellens_lamp
      - light.master_bedroom_overhead
      - light.master_bedroom_hallway_overhead
      - light.master_bathroom_vanity
      - light.hallway_overhead
      - light.kitchen_overhead
    name: Fluxer
    start_time: '7:00'
    stop_time: '23:00'
    start_colortemp: 4000
    sunset_colortemp: 3000
    stop_colortemp: 1900
    brightness: 128
    mode: xy
    transition: 30
    interval: 60
