homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

http:
frontend:
  themes: !include_dir_merge_named themes
lovelace:
  mode: yaml
config:
system_health:
updater:
mobile_app:
ios:
history:
logbook:
sun:

recorder:
  db_url: !secret mysql_url

binary_sensor:
- platform: template
  sensors: !include_dir_merge_named binary_sensors

august: !include integrations/august.yaml
automation: !include_dir_merge_list automations
cover: !include integrations/cover.yaml
dyson: !include integrations/dyson.yaml
ecobee: !include integrations/ecobee.yaml
group: !include groups.yaml
homekit: !include integrations/homekit.yaml
input_boolean: !include integrations/input_boolean.yaml
scene: !include scenes.yaml
script: !include_dir_merge_named scripts
sensor: !include integrations/sensor.yaml
timer: !include integrations/timer.yaml
