# General configuration
homeassistant:
  customize: !include customize.yaml
  elevation: !secret home_elevation
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  name: !secret home_name
  time_zone: America/Los_Angeles
  unit_system: imperial

# Base configuration
automation: !include_dir_merge_list automations
config:
discovery:
frontend:
  themes: !include_dir_merge_named themes
history:
http:
  ssl_certificate: ssl/fullchain.pem
  ssl_key: ssl/privkey.pem
ios:
logbook:
mobile_app:
recorder:
script: !include_dir_merge_named scripts
sun:
system_health:
updater:

# Integrations
august: !include integrations/august.yaml
binary_sensor: !include integrations/binary_sensor.yaml
cover: !include integrations/cover.yaml
dyson: !include integrations/dyson.yaml
ecobee: !include integrations/ecobee.yaml
group: !include groups.yaml
homekit: !include integrations/homekit.yaml
input_boolean: !include integrations/input_boolean.yaml
light: !include integrations/light.yaml
scene: !include scenes.yaml
sensor: !include integrations/sensor.yaml
shell_command: !include integrations/shell_command.yaml
somfy_mylink: !include integrations/somfy_mylink.yaml
spotify: !include integrations/spotify.yaml
timer: !include integrations/timer.yaml
weather: !include integrations/weather.yaml
yeelight: !include integrations/yeelight.yaml
zone: !include integrations/zone.yaml
