homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes
lovelace:
  mode: yaml
config:
system_health:
http:
updater:
ios:
history:
logbook:
sun:

hacs:
  token: !secret github_access_token
  theme: true

binary_sensor:
- platform: template
  sensors: !include_dir_merge_named binary_sensors

august: !include platforms/august.yaml
dyson: !include platforms/dyson.yaml

sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - icon
      - temperature
      - precip_probability  
      - wind_speed
      - wind_bearing
      - sunrise_time
      - sunset_time
      - alerts
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: load_5m
      - type: processor_use

group: !include groups.yaml
automation: !include automations.yaml
script: !include_dir_merge_named scripts
scene: !include scenes.yaml
