homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

http:
frontend:
  themes: !include_dir_merge_named themes
lovelace:
  mode: yaml
config:
system_health:
updater:
mobile_app:
ios:
history:
logbook:
sun:

recorder:
  db_url: !secret mysql_url

hacs:
  token: !secret github_access_token

august:
  login_method: phone
  username: !secret august_username
  password: !secret august_password

automation: !include_dir_merge_list automations

cover: !include integrations/cover.yaml

dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: GB
  devices:
    - device_id: !secret dyson_fan_id
      device_ip: 10.0.0.60

ecobee:
  api_key: !secret ecobee_api_key

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key

binary_sensor: !include integrations/binary_sensor.yaml
group: !include groups.yaml
homekit: !include integrations/homekit.yaml
input_boolean: !include integrations/input_boolean.yaml
scene: !include scenes.yaml
script: !include_dir_merge_named scripts
sensor: !include integrations/sensor.yaml
timer: !include integrations/timer.yaml
zone: !include integrations/zone.yaml
