title: !secret home_name

resources:
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: module
  - url: /community_plugin/search-card/search-card.js
    type: module
  - url: /community_plugin/group-card/group-card.js
    type: module
  - url: /local/camera-card.js
    type: module

views:
  - !include ui/home.yaml
  - !include ui/switches.yaml
  - !include ui/status.yaml
  - !include ui/development.yaml
