- alias: 'Create weekly backup'
  initial_state: 'on'
  trigger:
    platform: time
    at: '02:00:00'
  condition:
    condition: time
    weekday:
      - sun
  action:
    service: hassio.snapshot_full
    data_template:
      name: "{{now().strftime('%Y-%m-%d')}}"
