- alias: Notify when batteries are low
  initial_state: 'on'
  trigger:
    - platform: time
      at: '09:00:00'
  condition:
    condition: template
    value_template: >
      {% set min_battery_level = 10 -%}
      {% set ns = namespace(found=false) -%}
      {% for entity_id in states.group.batteries.attributes.entity_id -%}
        {% if states(entity_id) != "unknown" and (states(entity_id) | replace("%","") | int) < min_battery_level -%}
          {% set ns.found = true -%}
        {% endif -%}
      {% endfor -%}
      {{ ns.found }}
  action:
    - service: notify.mobile_app_sams_iphone
      data_template:
        title: '🔋 Batteries are low'
        message: >-
          {%- set min_battery_level = 10 -%}
          {%- for entity_id in states.group.batteries.attributes.entity_id -%}
          {%- set parts = entity_id.split('.') -%}
          {%- if states(entity_id) != "unknown" and (states(entity_id) | replace("%","") | int) < min_battery_level -%}
          {{ states[parts[0]][parts[1]].name }} battery level is {{ states(entity_id) }}%.{{ '\n' }}
          {%- endif -%}
          {%- endfor -%}
        data:
          push:
            sound:
              name: default
          apns_headers:
            apns-collapse-id: batteries-low
