# When the front door opens, turn on the lights for a few minutes if it's dark out
- alias: Front door opened
  trigger:
  - platform: state
    entity_id: binary_sensor.front_door_open
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    - service: scene.create
      data:
        scene_id: front_porch_before
        snapshot_entities:
          - light.front_porch
          - light.stairs
    - service: scene.turn_on
      entity_id: scene.front_porch_on

# When the front door closes, restore the state of the lights
- alias: Front door closed
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_open
      from: 'on'
      to: 'off'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.front_porch_before
