- alias: "Toggle Ellen’s space heater"
  trigger:
    device_id: 4875879e6bb846b294822d756ffaa1e9
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  action:
    service: homeassistant.toggle
    entity_id: switch.ellens_space_heater
