- alias: Turn off fan in the morning on workdays
  initial_state: 'on'
  trigger:
    - platform: sun
      event: sunrise
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: fan.master_bedroom
