- alias: "Kitchen Switch - On"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_switch
      event: 1000
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_on

- alias: "Kitchen Switch - Off"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_switch
      event: 4000
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_off

- alias: "Kitchen Switch - Up"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_switch
      event: 2000
  action:
    service: cover.open_cover
    entity_id: cover.kitchen

- alias: "Kitchen Switch - Down"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_switch
      event: 3000
  action:
    service: cover.close_cover
    entity_id: cover.kitchen
