- alias: "Office Switch - On"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: office_switch
      event: 1000
  action:
    service: scene.turn_on
    entity_id: scene.office_on

- alias: "Office Switch - Off"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: office_switch
      event: 4000
  action:
    service: scene.turn_on
    entity_id: scene.office_off

- alias: "Turn on office closet light"
  trigger:
    # Closet opens
    - platform: state
      entity_id: binary_sensor.office_closet_door
      to: 'on'
    # Office switch - on
    - platform: event
      event_type: deconz_event
      event_data:
        id: office_switch
        event: 1000
  # Ensure the closet is open since it could’ve been an
  # office switch press but the door is closed
  condition:
    condition: state
    entity_id: binary_sensor.office_closet_door
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.office_closet_overhead

- alias: "Turn off office closet light"
  trigger:
    platform: state
    entity_id: binary_sensor.office_closet_door
    to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: light.office_closet_overhead

- alias: "Toggle space heater"
  trigger:
    # Office mini button
    platform: event
    event_type: deconz_event
    event_data:
      id: smart_switch
      event: 1002
  action:
    service: homeassistant.toggle
    entity_id: switch.space_heater
