- alias: "Office Switch - On"
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:02:d4:34:c0"
      command: "on"
  action:
    service: scene.turn_on
    entity_id: scene.office_on

- alias: "Office Switch - Off"
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:02:d4:34:c0"
      command: "off_with_effect"
  action:
    service: scene.turn_on
    entity_id: scene.office_off

- alias: "Turn on office closet light"
  trigger:
    platform: state
    entity_id: binary_sensor.office_closet_door
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.office_closet_overhead

- alias: "Turn off office closet light"
  trigger:
    platform: state
    entity_id: binary_sensor.office_closet_door
    to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: light.office_closet_overhead
