- id: leave-home
  alias: 'Turn off things when everyone leaves'
  trigger:
    - platform: state
      entity_id: group.family
      to: 'not_home'
  action:
    service: climate.set_preset_mode
    entity_id: climate.hallway
    data:
      preset_mode: Away

- alias: Turn off things when Sam leaves
  trigger:
    - platform: state
      entity_id: person.sam
      to: 'not_home'
  action:
    service: homeassistant.turn_off
    entity_id: switch.space_heater

- id: arrive-home
  alias: 'Turn on things when someone arrives'
  trigger:
    - platform: state
      entity_id: group.family
      to: 'home'
  action:
    service: climate.set_preset_mode
    entity_id: climate.hallway
    data:
      preset_mode: Home
