- alias: "Open shades on weekday mornings"
  trigger:
    - platform: sun
      event: sunrise
      offset: "01:00:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
  action:
    service: cover.open_cover
    entity_id:
      - cover.living_room
      - cover.dining_room
      - cover.office

- alias: "Close dining room shades in the evening"
  trigger:
    - platform: sun
      event: sunset
  condition:
    - condition: state
      entity_id: binary_sensor.dining_room_window
      state: 'off'
  action:
    service: cover.close_cover
    entity_id:
      - cover.dining_room

- alias: "Close master bedroom shades in the evening"
  trigger:
    - platform: sun
      event: sunset
  condition:
    - condition: state
      entity_id: binary_sensor.master_bedroom_window
      state: 'off'
  action:
    service: cover.close_cover
    entity_id:
      - cover.master_bedroom

- alias: "Close office shades in the evening"
  trigger:
    - platform: sun
      event: sunset
  condition:
    - condition: state
      entity_id: binary_sensor.office_window
      state: 'off'
  action:
    service: cover.close_cover
    entity_id:
      - cover.office

- alias: "Close living room shades in the evening"
  trigger:
    - platform: sun
      event: sunset
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.living_room_window_left
          state: 'off'
        - condition: state
          entity_id: binary_sensor.living_room_window_right
          state: 'off'
  action:
    service: cover.close_cover
    entity_id:
      - cover.office

- alias: "Close kitchen shades in the evening"
  trigger:
    - platform: sun
      event: sunset
  condition:
    - condition: state
      entity_id: binary_sensor.kitchen_window
      state: 'off'
  action:
    service: cover.close_cover
    entity_id:
      - cover.kitchen
