- alias: "Turn on smart plug"
  trigger:
    platform: state
    entity_id: sensor.mini_button
    to: 'single'
  action:
    service: homeassistant.turn_on
    entity_id: switch.smart_plug

- alias: "Turn off smart plug"
  trigger:
    platform: state
    entity_id: sensor.mini_button
    to: 'double'
  action:
    service: homeassistant.turn_off
    entity_id: switch.smart_plug
