- alias: "Office Switch - On"
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:02:d4:34:c0"
      command: "on"
  action:
    service: scene.turn_on
    entity_id: scene.office_on

- alias: "Office Switch - Off"
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:02:d4:34:c0"
      command: "off_with_effect"
  action:
    service: scene.turn_on
    entity_id: scene.office_off
