esphome:
  name: thermostat
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.0.0.61

captive_portal:
logger:
api:
ota:

switch:
  - platform: gpio
    id: heater
    pin: D0

sensor:
  - platform: dht
    pin: D1
    temperature:
      id: temperature
    humidity:
      id: humidity
    update_interval: 60s

climate:
  - platform: bang_bang
    name: "Thermostat"
    sensor: temperature
    default_target_temperature_low: 64 °F
    default_target_temperature_high: 72 °F
    heat_action:
      - switch.turn_on: heater
    idle_action:
      - switch.turn_off: heater
